services:
  - type: web
    name: url-redirect-scraper
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: API_SECRET
        generateValue: true
      - key: PUPPETEER_ARGS
        value: --no-sandbox,--disable-setuid-sandbox,--disable-dev-shm-usage,--disable-gpu,--single-process,--no-zygote
